# Generated by Django 3.2.8 on 2026-01-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='User',
            new_name='user',
        ),
    ]
